version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "adrianwedd"
    labels:
      - "dependencies"
      - "npm"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "adrianwedd"
    labels:
      - "dependencies"
      - "python"
